name: workroomc
favicon: null
layout_spectrum: 0.9517815629951656
typography_spectrum: 0.7808599062263966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7971984113100916
  lightness: 0.36989275459200144
  saturation: 0.19129904732108116
  rhythmicContrast: 0.43895679945126176
purpose: []
